### ISSUE TITLE
Broken link "ArgoCD GitOps Tutorial - Working with Kustomize"

### ISSUE THREAD

**Issue by Petrosz007** [aabouzaid/awesome-kustomize#5]
The Guides > Intermediate > [ArgoCD GitOps Tutorial - Working with Kustomize](https://developers.redhat.com/learning/learn:openshift:develop-gitops/resource/resources:working-kustomize) link is broken, RedHat's website returns a 404.

I don't know what the original article was, but on google I found this doc, not sure if this is the same one. https://redhat-scholars.github.io/argocd-tutorial/argocd-tutorial/03-kustomize.html

**Comment by aabouzaid** [comment]
@Petrosz007 thanks a lot for reporting this :ok_hand: 
I've fixed it in [abfd79f](https://github.com/aabouzaid/awesome-kustomize/commit/abfd79fcc490dff6f5d8c8cc148b674a381c9e2a).
